name: Tests
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    environment: CodeCov
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage
          pip install black
      - name: Check syntax and style
        run: black --check bot/*.py tests/*.py
      - name: Run tests and collect coverage
        run: |
          coverage run tests/tests.py
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
